name: Vector Upsert

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  vector-upsert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upsert vectors
        run: |
          curl -X POST \
            http://flowise-alb-2056808100.ap-south-1.elb.amazonaws.com/api/v1/vector/upsert/cc783114-df6c-485d-97c3-dd964107b486 \
            -H "Content-Type: application/json" \
            -d '{}'

      - name: Check response
        run: |
          response=$(curl -s -w "%{http_code}" -X POST \
            http://flowise-alb-2056808100.ap-south-1.elb.amazonaws.com/api/v1/vector/upsert/cc783114-df6c-485d-97c3-dd964107b486 \
            -H "Content-Type: application/json" \
            -d '{}')

          http_code="${response: -3}"
          body="${response%???}"

          echo "HTTP Status Code: $http_code"
          echo "Response Body: $body"

          if [ "$http_code" -eq 200 ]; then
            echo "✅ Vector upsert successful"
          else
            echo "❌ Vector upsert failed with status code: $http_code"
            exit 1
          fi
